import 'package:flutter/material.dart';

class StandingShooters extends StatefulWidget {
  @override
  _StandingShootersState createState() => _StandingShootersState();
}

class _StandingShootersState extends State<StandingShooters> {
  List playerList = [
    {
        "playerId":17094,
        "playerInfo":{
            "playerId":17094,
            "playerName":"阿圭罗",
            "otherName":"阿奎罗, 塞尔吉奥",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":17,
                "teamName":"曼城",
                "flag":"http://statics.itc.cn/football/teamicon/17.png",
                "group":null
            },
            "photo":null,
            "age":30,
            "birthDate":"1988-06-02"
        },
        "games":2,
        "minutes":0,
        "goals":3,
        "assists":0,
        "pGoals":0,
        "passes":33,
        "shortPasses":5,
        "mediumPasses":28,
        "longPasses":0,
        "tackles":9,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":217704,
        "playerInfo":{
            "playerId":217704,
            "playerName":"马内",
            "otherName":"马内, 萨迪奥",
            "number":0,
            "positionStr":null,
            "position":0,
            "teamInfo":{
                "teamId":44,
                "teamName":"利物浦",
                "flag":"http://statics.itc.cn/football/teamicon/44.png",
                "group":null
            },
            "photo":null,
            "age":0,
            "birthDate":null
        },
        "games":2,
        "minutes":0,
        "goals":3,
        "assists":0,
        "pGoals":0,
        "passes":60,
        "shortPasses":13,
        "mediumPasses":46,
        "longPasses":1,
        "tackles":6,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":992069,
        "playerInfo":{
            "playerId":992069,
            "playerName":"理查利森",
            "otherName":"理查利森",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":48,
                "teamName":"埃弗顿",
                "flag":"http://statics.itc.cn/football/teamicon/48.png",
                "group":null
            },
            "photo":null,
            "age":21,
            "birthDate":"1997-05-10"
        },
        "games":2,
        "minutes":0,
        "goals":3,
        "assists":0,
        "pGoals":0,
        "passes":43,
        "shortPasses":9,
        "mediumPasses":33,
        "longPasses":1,
        "tackles":9,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":113956,
        "playerInfo":{
            "playerId":113956,
            "playerName":null,
            "otherName":"威尔逊",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":60,
                "teamName":"伯恩茅斯",
                "flag":"http://statics.itc.cn/football/teamicon/60.png",
                "group":null
            },
            "photo":null,
            "age":26,
            "birthDate":"1992-02-27"
        },
        "games":2,
        "minutes":0,
        "goals":2,
        "assists":1,
        "pGoals":0,
        "passes":31,
        "shortPasses":9,
        "mediumPasses":22,
        "longPasses":0,
        "tackles":10,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":35428,
        "playerInfo":{
            "playerId":35428,
            "playerName":"佩德罗",
            "otherName":"佩德罗",
            "number":0,
            "positionStr":"midfielder",
            "position":3,
            "teamInfo":{
                "teamId":38,
                "teamName":"切尔西",
                "flag":"http://statics.itc.cn/football/teamicon/38.png",
                "group":null
            },
            "photo":null,
            "age":31,
            "birthDate":"1987-07-28"
        },
        "games":2,
        "minutes":0,
        "goals":2,
        "assists":0,
        "pGoals":0,
        "passes":87,
        "shortPasses":16,
        "mediumPasses":71,
        "longPasses":0,
        "tackles":4,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":122701,
        "playerInfo":{
            "playerId":122701,
            "playerName":"罗伯托-佩雷拉",
            "otherName":"佩雷拉, 罗伯托",
            "number":0,
            "positionStr":"midfielder",
            "position":3,
            "teamInfo":{
                "teamId":24,
                "teamName":"沃特福德",
                "flag":"http://statics.itc.cn/football/teamicon/24.png",
                "group":null
            },
            "photo":null,
            "age":27,
            "birthDate":"1991-01-07"
        },
        "games":2,
        "minutes":0,
        "goals":2,
        "assists":0,
        "pGoals":0,
        "passes":46,
        "shortPasses":7,
        "mediumPasses":38,
        "longPasses":1,
        "tackles":6,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":111802,
        "playerInfo":{
            "playerId":111802,
            "playerName":"博格巴",
            "otherName":"庞格巴, 保罗",
            "number":0,
            "positionStr":"midfielder",
            "position":3,
            "teamInfo":{
                "teamId":35,
                "teamName":"曼联",
                "flag":"http://statics.itc.cn/football/teamicon/35.png",
                "group":null
            },
            "photo":null,
            "age":25,
            "birthDate":"1993-03-15"
        },
        "games":2,
        "minutes":0,
        "goals":2,
        "assists":0,
        "pGoals":0,
        "passes":117,
        "shortPasses":15,
        "mediumPasses":98,
        "longPasses":4,
        "tackles":12,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":791,
        "playerInfo":{
            "playerId":791,
            "playerName":"米尔纳",
            "otherName":"米尔纳, 詹姆斯",
            "number":0,
            "positionStr":null,
            "position":0,
            "teamInfo":{
                "teamId":44,
                "teamName":"利物浦",
                "flag":"http://statics.itc.cn/football/teamicon/44.png",
                "group":null
            },
            "photo":null,
            "age":0,
            "birthDate":null
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":1,
        "pGoals":0,
        "passes":143,
        "shortPasses":18,
        "mediumPasses":122,
        "longPasses":3,
        "tackles":12,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":22109,
        "playerInfo":{
            "playerId":22109,
            "playerName":"迪尼",
            "otherName":"迪尼, 特洛伊",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":24,
                "teamName":"沃特福德",
                "flag":"http://statics.itc.cn/football/teamicon/24.png",
                "group":null
            },
            "photo":null,
            "age":30,
            "birthDate":"1988-06-29"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":1,
        "pGoals":0,
        "passes":32,
        "shortPasses":5,
        "mediumPasses":26,
        "longPasses":1,
        "tackles":3,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":280955,
        "playerInfo":{
            "playerId":280955,
            "playerName":"鲁本-内维斯",
            "otherName":"鲁本·内维斯",
            "number":0,
            "positionStr":"midfielder",
            "position":3,
            "teamInfo":{
                "teamId":3,
                "teamName":"狼队",
                "flag":"http://statics.itc.cn/football/teamicon/3.png",
                "group":null
            },
            "photo":null,
            "age":21,
            "birthDate":"1997-03-13"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":1,
        "pGoals":0,
        "passes":133,
        "shortPasses":1,
        "mediumPasses":129,
        "longPasses":3,
        "tackles":6,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":69408,
        "playerInfo":{
            "playerId":69408,
            "playerName":"M-阿隆索",
            "otherName":"阿隆索, 马科斯",
            "number":0,
            "positionStr":"defender",
            "position":4,
            "teamInfo":{
                "teamId":38,
                "teamName":"切尔西",
                "flag":"http://statics.itc.cn/football/teamicon/38.png",
                "group":null
            },
            "photo":null,
            "age":27,
            "birthDate":"1990-12-28"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":1,
        "pGoals":0,
        "passes":152,
        "shortPasses":13,
        "mediumPasses":138,
        "longPasses":1,
        "tackles":10,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":138261,
        "playerInfo":{
            "playerId":138261,
            "playerName":"弗雷泽",
            "otherName":"弗拉塞尔, 瑞恩",
            "number":0,
            "positionStr":"midfielder",
            "position":3,
            "teamInfo":{
                "teamId":60,
                "teamName":"伯恩茅斯",
                "flag":"http://statics.itc.cn/football/teamicon/60.png",
                "group":null
            },
            "photo":null,
            "age":24,
            "birthDate":"1994-02-24"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":1,
        "pGoals":0,
        "passes":54,
        "shortPasses":8,
        "mediumPasses":45,
        "longPasses":1,
        "tackles":5,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":10501,
        "playerInfo":{
            "playerId":10501,
            "playerName":"沃尔科特",
            "otherName":"沃尔科特, 西奥",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":48,
                "teamName":"埃弗顿",
                "flag":"http://statics.itc.cn/football/teamicon/48.png",
                "group":null
            },
            "photo":null,
            "age":29,
            "birthDate":"1989-03-16"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":1,
        "pGoals":0,
        "passes":29,
        "shortPasses":9,
        "mediumPasses":20,
        "longPasses":0,
        "tackles":9,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":37151,
        "playerInfo":{
            "playerId":37151,
            "playerName":"姆希塔良",
            "otherName":"Mkhitaryan, Henrikh",
            "number":0,
            "positionStr":"midfielder",
            "position":3,
            "teamInfo":{
                "teamId":42,
                "teamName":"阿森纳",
                "flag":"http://statics.itc.cn/football/teamicon/42.png",
                "group":null
            },
            "photo":null,
            "age":29,
            "birthDate":"1989-01-21"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":1,
        "pGoals":0,
        "passes":44,
        "shortPasses":3,
        "mediumPasses":41,
        "longPasses":0,
        "tackles":8,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":78893,
        "playerInfo":{
            "playerId":78893,
            "playerName":"卢卡库",
            "otherName":"卢卡库, 罗梅鲁",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":35,
                "teamName":"曼联",
                "flag":"http://statics.itc.cn/football/teamicon/35.png",
                "group":null
            },
            "photo":null,
            "age":25,
            "birthDate":"1993-05-13"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":14,
        "shortPasses":3,
        "mediumPasses":11,
        "longPasses":0,
        "tackles":1,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":125407,
        "playerInfo":{
            "playerId":125407,
            "playerName":"莫拉塔",
            "otherName":"莫拉塔, 阿尔瓦罗",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":38,
                "teamName":"切尔西",
                "flag":"http://statics.itc.cn/football/teamicon/38.png",
                "group":null
            },
            "photo":null,
            "age":25,
            "birthDate":"1992-10-23"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":32,
        "shortPasses":5,
        "mediumPasses":27,
        "longPasses":0,
        "tackles":6,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":69256,
        "playerInfo":{
            "playerId":69256,
            "playerName":"特里皮尔",
            "otherName":"特里皮尔, 基兰",
            "number":0,
            "positionStr":"defender",
            "position":4,
            "teamInfo":{
                "teamId":33,
                "teamName":"热刺",
                "flag":"http://statics.itc.cn/football/teamicon/33.png",
                "group":null
            },
            "photo":null,
            "age":27,
            "birthDate":"1990-09-19"
        },
        "games":1,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":62,
        "shortPasses":7,
        "mediumPasses":54,
        "longPasses":1,
        "tackles":5,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":108579,
        "playerInfo":{
            "playerId":108579,
            "playerName":"哈里-凯恩",
            "otherName":"卡内, 哈里",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":33,
                "teamName":"热刺",
                "flag":"http://statics.itc.cn/football/teamicon/33.png",
                "group":null
            },
            "photo":null,
            "age":25,
            "birthDate":"1993-07-28"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":47,
        "shortPasses":9,
        "mediumPasses":35,
        "longPasses":3,
        "tackles":11,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":192442,
        "playerInfo":{
            "playerId":192442,
            "playerName":"吉梅内斯",
            "otherName":"吉梅内斯, 劳尔",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":3,
                "teamName":"狼队",
                "flag":"http://statics.itc.cn/football/teamicon/3.png",
                "group":null
            },
            "photo":null,
            "age":27,
            "birthDate":"1991-05-05"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":43,
        "shortPasses":7,
        "mediumPasses":36,
        "longPasses":0,
        "tackles":6,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":193554,
        "playerInfo":{
            "playerId":193554,
            "playerName":"威尔-休斯",
            "otherName":"休斯, 威尔",
            "number":0,
            "positionStr":"midfielder",
            "position":3,
            "teamInfo":{
                "teamId":24,
                "teamName":"沃特福德",
                "flag":"http://statics.itc.cn/football/teamicon/24.png",
                "group":null
            },
            "photo":null,
            "age":23,
            "birthDate":"1995-04-07"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":43,
        "shortPasses":9,
        "mediumPasses":34,
        "longPasses":0,
        "tackles":6,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":20097,
        "playerInfo":{
            "playerId":20097,
            "playerName":"格伦-穆雷",
            "otherName":"穆雷, 格伦",
            "number":0,
            "positionStr":null,
            "position":0,
            "teamInfo":{
                "teamId":30,
                "teamName":"布莱顿",
                "flag":"http://statics.itc.cn/football/teamicon/30.png",
                "group":null
            },
            "photo":null,
            "age":0,
            "birthDate":null
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":26,
        "shortPasses":5,
        "mediumPasses":20,
        "longPasses":1,
        "tackles":2,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":148710,
        "playerInfo":{
            "playerId":148710,
            "playerName":"施鲁普",
            "otherName":"施鲁普, 杰弗瑞",
            "number":0,
            "positionStr":null,
            "position":0,
            "teamInfo":{
                "teamId":7,
                "teamName":"水晶宫",
                "flag":"http://statics.itc.cn/football/teamicon/7.png",
                "group":null
            },
            "photo":null,
            "age":0,
            "birthDate":null
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":36,
        "shortPasses":2,
        "mediumPasses":32,
        "longPasses":2,
        "tackles":7,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":159665,
        "playerInfo":{
            "playerId":159665,
            "playerName":"萨拉赫",
            "otherName":"萨拉赫, 穆罕默德",
            "number":0,
            "positionStr":null,
            "position":0,
            "teamInfo":{
                "teamId":44,
                "teamName":"利物浦",
                "flag":"http://statics.itc.cn/football/teamicon/44.png",
                "group":null
            },
            "photo":null,
            "age":0,
            "birthDate":null
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":37,
        "shortPasses":12,
        "mediumPasses":25,
        "longPasses":0,
        "tackles":6,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":352770,
        "playerInfo":{
            "playerId":352770,
            "playerName":"伊沃比",
            "otherName":"亚历克斯,伊沃比",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":42,
                "teamName":"阿森纳",
                "flag":"http://statics.itc.cn/football/teamicon/42.png",
                "group":null
            },
            "photo":null,
            "age":22,
            "birthDate":"1996-05-03"
        },
        "games":1,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":12,
        "shortPasses":0,
        "mediumPasses":12,
        "longPasses":0,
        "tackles":2,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":835751,
        "playerInfo":{
            "playerId":835751,
            "playerName":"热苏斯",
            "otherName":"热苏斯",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":17,
                "teamName":"曼城",
                "flag":"http://statics.itc.cn/football/teamicon/17.png",
                "group":null
            },
            "photo":null,
            "age":21,
            "birthDate":"1997-04-03"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":32,
        "shortPasses":6,
        "mediumPasses":26,
        "longPasses":0,
        "tackles":7,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":234148,
        "playerInfo":{
            "playerId":234148,
            "playerName":"坎特",
            "otherName":"坎特",
            "number":0,
            "positionStr":null,
            "position":0,
            "teamInfo":{
                "teamId":38,
                "teamName":"切尔西",
                "flag":"http://statics.itc.cn/football/teamicon/38.png",
                "group":null
            },
            "photo":null,
            "age":0,
            "birthDate":null
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":99,
        "shortPasses":7,
        "mediumPasses":92,
        "longPasses":0,
        "tackles":2,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":138534,
        "playerInfo":{
            "playerId":138534,
            "playerName":"斯特林",
            "otherName":"斯特林, 拉希姆",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":17,
                "teamName":"曼城",
                "flag":"http://statics.itc.cn/football/teamicon/17.png",
                "group":null
            },
            "photo":null,
            "age":23,
            "birthDate":"1994-12-08"
        },
        "games":1,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":18,
        "shortPasses":2,
        "mediumPasses":16,
        "longPasses":0,
        "tackles":5,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":331209,
        "playerInfo":{
            "playerId":331209,
            "playerName":"B-席尔瓦",
            "otherName":"Silva, Bernardo",
            "number":0,
            "positionStr":"midfielder",
            "position":3,
            "teamInfo":{
                "teamId":17,
                "teamName":"曼城",
                "flag":"http://statics.itc.cn/football/teamicon/17.png",
                "group":null
            },
            "photo":null,
            "age":24,
            "birthDate":"1994-08-10"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":83,
        "shortPasses":7,
        "mediumPasses":75,
        "longPasses":1,
        "tackles":5,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":55570,
        "playerInfo":{
            "playerId":55570,
            "playerName":"达菲",
            "otherName":"达菲, 谢恩",
            "number":0,
            "positionStr":"defender",
            "position":4,
            "teamInfo":{
                "teamId":30,
                "teamName":"布莱顿",
                "flag":"http://statics.itc.cn/football/teamicon/30.png",
                "group":null
            },
            "photo":null,
            "age":26,
            "birthDate":"1992-01-01"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":47,
        "shortPasses":5,
        "mediumPasses":38,
        "longPasses":4,
        "tackles":3,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":130181,
        "playerInfo":{
            "playerId":130181,
            "playerName":"因斯",
            "otherName":"因格斯, 丹尼",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":45,
                "teamName":"南安普顿",
                "flag":"http://statics.itc.cn/football/teamicon/45.png",
                "group":null
            },
            "photo":null,
            "age":26,
            "birthDate":"1992-07-23"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":27,
        "shortPasses":6,
        "mediumPasses":21,
        "longPasses":0,
        "tackles":2,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":42707,
        "playerInfo":{
            "playerId":42707,
            "playerName":"库克",
            "otherName":"库克, 斯蒂夫",
            "number":0,
            "positionStr":"defender",
            "position":4,
            "teamInfo":{
                "teamId":60,
                "teamName":"伯恩茅斯",
                "flag":"http://statics.itc.cn/football/teamicon/60.png",
                "group":null
            },
            "photo":null,
            "age":27,
            "birthDate":"1991-04-19"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":75,
        "shortPasses":3,
        "mediumPasses":71,
        "longPasses":1,
        "tackles":2,
        "fouls":0,
        "clears":1,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":280565,
        "playerInfo":{
            "playerId":280565,
            "playerName":"斯坦科维奇",
            "otherName":"约恩·斯坦科维奇",
            "number":0,
            "positionStr":"defender",
            "position":4,
            "teamInfo":{
                "teamId":59,
                "teamName":"哈德斯菲尔德",
                "flag":"http://statics.itc.cn/football/teamicon/59.png",
                "group":null
            },
            "photo":null,
            "age":22,
            "birthDate":"1996-01-14"
        },
        "games":1,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":9,
        "shortPasses":1,
        "mediumPasses":7,
        "longPasses":1,
        "tackles":2,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":145188,
        "playerInfo":{
            "playerId":145188,
            "playerName":"塔尔科夫斯基",
            "otherName":"塔尔科夫斯基, 詹姆斯",
            "number":0,
            "positionStr":"defender",
            "position":4,
            "teamInfo":{
                "teamId":6,
                "teamName":"伯恩利",
                "flag":"http://statics.itc.cn/football/teamicon/6.png",
                "group":null
            },
            "photo":null,
            "age":25,
            "birthDate":"1992-11-19"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":82,
        "shortPasses":3,
        "mediumPasses":77,
        "longPasses":2,
        "tackles":4,
        "fouls":0,
        "clears":1,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":190839,
        "playerInfo":{
            "playerId":190839,
            "playerName":"卢克-肖",
            "otherName":"肖, 卢克",
            "number":0,
            "positionStr":"defender",
            "position":4,
            "teamInfo":{
                "teamId":35,
                "teamName":"曼联",
                "flag":"http://statics.itc.cn/football/teamicon/35.png",
                "group":null
            },
            "photo":null,
            "age":23,
            "birthDate":"1995-07-12"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":121,
        "shortPasses":16,
        "mediumPasses":104,
        "longPasses":1,
        "tackles":9,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":192144,
        "playerInfo":{
            "playerId":192144,
            "playerName":"米特洛维奇",
            "otherName":"亚历山大,米特罗维奇",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":43,
                "teamName":"富勒姆",
                "flag":"http://statics.itc.cn/football/teamicon/43.png",
                "group":null
            },
            "photo":null,
            "age":23,
            "birthDate":"1994-09-16"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":29,
        "shortPasses":2,
        "mediumPasses":27,
        "longPasses":0,
        "tackles":3,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":356398,
        "playerInfo":{
            "playerId":356398,
            "playerName":null,
            "otherName":"詹姆斯·麦迪逊",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":31,
                "teamName":"莱斯特城",
                "flag":"http://statics.itc.cn/football/teamicon/31.png",
                "group":null
            },
            "photo":null,
            "age":21,
            "birthDate":"1996-11-23"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":51,
        "shortPasses":14,
        "mediumPasses":37,
        "longPasses":0,
        "tackles":16,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":198028,
        "playerInfo":{
            "playerId":198028,
            "playerName":"阿里",
            "otherName":"阿利, 巴米德尔",
            "number":0,
            "positionStr":"midfielder",
            "position":3,
            "teamInfo":{
                "teamId":33,
                "teamName":"热刺",
                "flag":"http://statics.itc.cn/football/teamicon/33.png",
                "group":null
            },
            "photo":null,
            "age":22,
            "birthDate":"1996-04-11"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":88,
        "shortPasses":15,
        "mediumPasses":71,
        "longPasses":2,
        "tackles":13,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":73951,
        "playerInfo":{
            "playerId":73951,
            "playerName":"安德烈-格雷",
            "otherName":"安德烈,格雷",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":24,
                "teamName":"沃特福德",
                "flag":"http://statics.itc.cn/football/teamicon/24.png",
                "group":null
            },
            "photo":null,
            "age":27,
            "birthDate":"1991-06-26"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":12,
        "shortPasses":4,
        "mediumPasses":8,
        "longPasses":0,
        "tackles":1,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":21927,
        "playerInfo":{
            "playerId":21927,
            "playerName":"阿瑙托维奇",
            "otherName":"阿纳乌托维奇, 马尔科",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":37,
                "teamName":"西汉姆联",
                "flag":"http://statics.itc.cn/football/teamicon/37.png",
                "group":null
            },
            "photo":null,
            "age":29,
            "birthDate":"1989-04-19"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":28,
        "shortPasses":11,
        "mediumPasses":17,
        "longPasses":0,
        "tackles":6,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":48480,
        "playerInfo":{
            "playerId":48480,
            "playerName":"格罗斯",
            "otherName":"格罗斯, 帕斯卡",
            "number":0,
            "positionStr":"midfielder",
            "position":3,
            "teamInfo":{
                "teamId":30,
                "teamName":"布莱顿",
                "flag":"http://statics.itc.cn/football/teamicon/30.png",
                "group":null
            },
            "photo":null,
            "age":27,
            "birthDate":"1991-06-15"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":33,
        "shortPasses":3,
        "mediumPasses":28,
        "longPasses":2,
        "tackles":6,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":16921,
        "playerInfo":{
            "playerId":16921,
            "playerName":"维尔通亨",
            "otherName":"扬·维尔通亨",
            "number":0,
            "positionStr":"defender",
            "position":4,
            "teamInfo":{
                "teamId":33,
                "teamName":"热刺",
                "flag":"http://statics.itc.cn/football/teamicon/33.png",
                "group":null
            },
            "photo":null,
            "age":31,
            "birthDate":"1987-04-24"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":157,
        "shortPasses":11,
        "mediumPasses":145,
        "longPasses":1,
        "tackles":5,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":173827,
        "playerInfo":{
            "playerId":173827,
            "playerName":"瓦尔迪",
            "otherName":"杰米, 瓦迪",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":31,
                "teamName":"莱斯特城",
                "flag":"http://statics.itc.cn/football/teamicon/31.png",
                "group":null
            },
            "photo":null,
            "age":31,
            "birthDate":"1987-01-11"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":10,
        "shortPasses":2,
        "mediumPasses":8,
        "longPasses":0,
        "tackles":3,
        "fouls":0,
        "clears":1,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":20963,
        "playerInfo":{
            "playerId":20963,
            "playerName":"斯图里奇",
            "otherName":"斯图里奇, 丹尼尔",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":44,
                "teamName":"利物浦",
                "flag":"http://statics.itc.cn/football/teamicon/44.png",
                "group":null
            },
            "photo":null,
            "age":28,
            "birthDate":"1989-09-01"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":5,
        "shortPasses":2,
        "mediumPasses":3,
        "longPasses":0,
        "tackles":0,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":149710,
        "playerInfo":{
            "playerId":149710,
            "playerName":"卢卡斯",
            "otherName":"卢卡斯",
            "number":0,
            "positionStr":"midfielder",
            "position":3,
            "teamInfo":{
                "teamId":33,
                "teamName":"热刺",
                "flag":"http://statics.itc.cn/football/teamicon/33.png",
                "group":null
            },
            "photo":null,
            "age":26,
            "birthDate":"1992-08-13"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":46,
        "shortPasses":20,
        "mediumPasses":26,
        "longPasses":0,
        "tackles":5,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":111850,
        "playerInfo":{
            "playerId":111850,
            "playerName":"扎哈",
            "otherName":"扎哈, 威尔弗雷德",
            "number":0,
            "positionStr":"midfielder",
            "position":3,
            "teamInfo":{
                "teamId":7,
                "teamName":"水晶宫",
                "flag":"http://statics.itc.cn/football/teamicon/7.png",
                "group":null
            },
            "photo":null,
            "age":25,
            "birthDate":"1992-11-10"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":43,
        "shortPasses":11,
        "mediumPasses":31,
        "longPasses":1,
        "tackles":19,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":132874,
        "playerInfo":{
            "playerId":132874,
            "playerName":"若日尼奥",
            "otherName":"乔治尼奥, 弗雷利奥-菲尔霍",
            "number":0,
            "positionStr":"midfielder",
            "position":3,
            "teamInfo":{
                "teamId":38,
                "teamName":"切尔西",
                "flag":"http://statics.itc.cn/football/teamicon/38.png",
                "group":null
            },
            "photo":null,
            "age":26,
            "birthDate":"1991-12-20"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":138,
        "shortPasses":14,
        "mediumPasses":123,
        "longPasses":1,
        "tackles":1,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":69418,
        "playerInfo":{
            "playerId":69418,
            "playerName":"何塞卢",
            "otherName":"乔塞鲁",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":39,
                "teamName":"纽卡斯尔",
                "flag":"http://statics.itc.cn/football/teamicon/39.png",
                "group":null
            },
            "photo":null,
            "age":28,
            "birthDate":"1990-03-27"
        },
        "games":2,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":23,
        "shortPasses":8,
        "mediumPasses":15,
        "longPasses":0,
        "tackles":5,
        "fouls":0,
        "clears":1,
        "rCards":0,
        "yCards":0
    },
    {
        "playerId":11781,
        "playerInfo":{
            "playerId":11781,
            "playerName":"大卫-席尔瓦",
            "otherName":"席尔瓦, 大卫",
            "number":0,
            "positionStr":"forward",
            "position":2,
            "teamInfo":{
                "teamId":17,
                "teamName":"曼城",
                "flag":"http://statics.itc.cn/football/teamicon/17.png",
                "group":null
            },
            "photo":null,
            "age":32,
            "birthDate":"1986-01-08"
        },
        "games":1,
        "minutes":0,
        "goals":1,
        "assists":0,
        "pGoals":0,
        "passes":46,
        "shortPasses":4,
        "mediumPasses":42,
        "longPasses":0,
        "tackles":0,
        "fouls":0,
        "clears":0,
        "rCards":0,
        "yCards":0
    }
];

  Container _buildTitleSection() {
    return Container(
            color: Colors.grey,
            padding: EdgeInsets.symmetric(horizontal: 15.0),
            height: 36.0,
            child: Row(
              children: [
                Expanded(
                  flex: 2,
                  child: Text('球员'),
                ),
                Expanded(
                  flex: 3,
                  child: Row(children: [
                    Expanded(
                      flex: 1,
                      child: Text('球队', textAlign: TextAlign.center),
                    ),
                    Expanded(
                      flex: 1,
                      child: Text('进球', textAlign: TextAlign.center),
                    ),
                  ]),
                )
              ],
            ));
  }

  Container _getItemWidget(item) {
    return Container(
        height: 50.0,
        padding: EdgeInsets.symmetric(horizontal: 15.0),
        color: item['bg'],
        child: Row(
          children: [
            Expanded(
                flex: 2,
                child: Row(
                  children: <Widget>[
                    Container(
                      width: 18.0,
                      child: Text(item['rank'], textAlign: TextAlign.center),
                    ),
                    Container(
                      width: 6 * 12.0,
                      padding: EdgeInsets.only(left: 2.0),
                      child: Text(item['playerName'], softWrap:true, overflow: TextOverflow.ellipsis,)
                    )
                    
                  ],
                )),
            Expanded(
              flex: 3,
              child: Row(children: [
                Expanded(
                  flex: 1,
                  child: Text(item['playerInfo']['teamInfo']['teamName'], textAlign: TextAlign.center),
                ),
                Expanded(
                  flex: 1,
                  child: Text('${item["goals"]}', textAlign: TextAlign.center),
                ),
              ]),
            )
          ],
        ));
  }

  List<Widget> _getTeamItem() {
    Color bg;
    List formatList = [];
    var item;
    int trueRank = 1;
    int currentNum = 0;
    for (var i = 0; i < playerList.length; i++) {
      item = playerList[i];
      // 处理排名
      if (currentNum == 0) {
        currentNum = item['goals'];
      } 
      if (item['goals'] < currentNum) {
        currentNum = item['goals'];
        trueRank = i + 1;
      }
      item['rank'] = trueRank.toString();
      // 处理 bg
      if (i % 2 == 1) {
        bg = Colors.grey;
      } else {
        bg = Colors.white;
      }
      item['bg'] = bg;
      // 处理 playerName
      item['playerName'] = item['playerInfo']['playerName'] != null ?  item['playerInfo']['playerName'] : item['playerInfo']['otherName'];

      formatList.add(item);
    }
    return formatList.map((item) {
      return new Container(
        child: _getItemWidget(item),
      );
    }).toList();
  }

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        _buildTitleSection(),
        Container(
            child: Column(
          children: _getTeamItem(),
        )),
        //
      ],
    );
  }
}